/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pim4.unip;

/**
 *
 * @author sdjma
 */
public class jifpesquisar extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifpesquisar
     */
    public jifpesquisar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpfconsultacliente = new javax.swing.JLabel();
        txtConsultacliente = new javax.swing.JTextField();
        btnConsultarcliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNumeroconta = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Pesquisa ");
        getContentPane().setLayout(null);

        lblCpfconsultacliente.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblCpfconsultacliente.setText("CPF ou CNPJ");
        getContentPane().add(lblCpfconsultacliente);
        lblCpfconsultacliente.setBounds(170, 120, 100, 20);
        getContentPane().add(txtConsultacliente);
        txtConsultacliente.setBounds(120, 160, 200, 30);

        btnConsultarcliente.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnConsultarcliente.setText("Consultar");
        btnConsultarcliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnConsultarcliente);
        btnConsultarcliente.setBounds(160, 220, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sdjma\\Downloads\\marcalogo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 144, 70);

        lblNumeroconta.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblNumeroconta.setText("Número da Conta ");
        getContentPane().add(lblNumeroconta);
        lblNumeroconta.setBounds(150, 290, 150, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 330, 200, 30);

        setBounds(0, 0, 456, 493);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCpfconsultacliente;
    private javax.swing.JLabel lblNumeroconta;
    private javax.swing.JTextField txtConsultacliente;
    // End of variables declaration//GEN-END:variables
}
