/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pim4.unip;

/**
 *
 * @author sdjma
 */
public class jifpesquisar extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifpesquisar
     */
    public jifpesquisar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblcpfoucnpj = new javax.swing.JLabel();
        txtcpfoucnpj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblou = new javax.swing.JLabel();
        txtnumerodaconta = new javax.swing.JTextField();
        btnconsultarcliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Pesquisa ");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sdjma\\Downloads\\marcalogo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(134, 40, 140, 60);

        lblcpfoucnpj.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        lblcpfoucnpj.setText("Digite o CPF ou CNPJ");
        getContentPane().add(lblcpfoucnpj);
        lblcpfoucnpj.setBounds(20, 120, 220, 40);

        txtcpfoucnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfoucnpjActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpfoucnpj);
        txtcpfoucnpj.setBounds(190, 130, 140, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel2.setText("Digite o número da conta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 210, 170, 20);

        lblou.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        lblou.setText("ou");
        getContentPane().add(lblou);
        lblou.setBounds(80, 180, 34, 14);
        getContentPane().add(txtnumerodaconta);
        txtnumerodaconta.setBounds(190, 210, 140, 20);

        btnconsultarcliente.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnconsultarcliente.setText("Consultar");
        btnconsultarcliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconsultarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarclienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultarcliente);
        btnconsultarcliente.setBounds(160, 300, 100, 30);

        setBounds(0, 0, 456, 493);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarclienteActionPerformed
JFtelaexibicaopesquisacliente obj = new JFtelaexibicaopesquisacliente();
obj.setVisible(true);
    }//GEN-LAST:event_btnconsultarclienteActionPerformed

    private void txtcpfoucnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfoucnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfoucnpjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultarcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblcpfoucnpj;
    private javax.swing.JLabel lblou;
    private javax.swing.JTextField txtcpfoucnpj;
    private javax.swing.JTextField txtnumerodaconta;
    // End of variables declaration//GEN-END:variables
}
