/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pim4.unip;

/**
 *
 * @author sdjma
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCliente = new javax.swing.JMenu();
        jPesquisar = new javax.swing.JMenuItem();
        jFuncionarios = new javax.swing.JMenu();
        jIncluir2 = new javax.swing.JMenuItem();
        jPesquisar2 = new javax.swing.JMenuItem();
        jMoedas = new javax.swing.JMenu();
        jPesquisar3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jdpprincipal);
        jdpprincipal.setBounds(0, 0, 980, 570);

        jCliente.setText("Clientes");

        jPesquisar.setText("Pesquisar ");
        jPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarActionPerformed(evt);
            }
        });
        jCliente.add(jPesquisar);

        jMenuBar1.add(jCliente);

        jFuncionarios.setText("Funcionários");

        jIncluir2.setText("Incluir");
        jIncluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncluir2ActionPerformed(evt);
            }
        });
        jFuncionarios.add(jIncluir2);

        jPesquisar2.setText("Pesquisar");
        jPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisar2ActionPerformed(evt);
            }
        });
        jFuncionarios.add(jPesquisar2);

        jMenuBar1.add(jFuncionarios);

        jMoedas.setText("Moedas");

        jPesquisar3.setText("Pesquisar");
        jPesquisar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisar3ActionPerformed(evt);
            }
        });
        jMoedas.add(jPesquisar3);

        jMenuBar1.add(jMoedas);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 995, 601);
    }// </editor-fold>//GEN-END:initComponents

    private void jPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarActionPerformed
jifpesquisar obj=new jifpesquisar();
jdpprincipal.add(obj);
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisarActionPerformed

    private void jIncluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncluir2ActionPerformed
jifincluir2 obj=new jifincluir2();
jdpprincipal.add(obj);
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jIncluir2ActionPerformed

    private void jPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisar2ActionPerformed
jifpesquisar2 obj=new jifpesquisar2();
jdpprincipal.add(obj);
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisar2ActionPerformed

    private void jPesquisar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisar3ActionPerformed
jifpesquisar3 obj=new jifpesquisar3();
jdpprincipal.add(obj);
obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCliente;
    private javax.swing.JMenu jFuncionarios;
    private javax.swing.JMenuItem jIncluir2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMoedas;
    private javax.swing.JMenuItem jPesquisar;
    private javax.swing.JMenuItem jPesquisar2;
    private javax.swing.JMenuItem jPesquisar3;
    private javax.swing.JDesktopPane jdpprincipal;
    // End of variables declaration//GEN-END:variables
}
