/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pimquarto.unip;

/**
 *
 * @author sdjma
 */
public class jifconsultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifconsultas
     */
    public jifconsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtN1 = new javax.swing.JTextField();
        btnConsulta1 = new javax.swing.JButton();
        lblSolicitar = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Consultas ");
        getContentPane().setLayout(null);
        getContentPane().add(txtN1);
        txtN1.setBounds(60, 150, 270, 36);

        btnConsulta1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnConsulta1.setText("Consultar ");
        getContentPane().add(btnConsulta1);
        btnConsulta1.setBounds(60, 220, 270, 40);

        lblSolicitar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblSolicitar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSolicitar.setText("Número de Solicitação ");
        getContentPane().add(lblSolicitar);
        lblSolicitar.setBounds(60, 100, 270, 26);

        setBounds(0, 0, 412, 458);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta1;
    private javax.swing.JLabel lblSolicitar;
    private javax.swing.JTextField txtN1;
    // End of variables declaration//GEN-END:variables
}
