/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pimquarto.unip;

/**
 *
 * @author sdjma
 */
public class jifgerenciar extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifgerenciar
     */
    public jifgerenciar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Gerenciamento ");
        getContentPane().setLayout(null);
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 180, 130, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 90, 190, 50);

        setBounds(0, 0, 410, 421);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
